environment: production
chdir: /stor/www/public/bkrsta.co.cc/apps/raspored
address: 127.0.0.1
user: bkrsta
group: users
port: 4008
pid: /stor/www/public/bkrsta.co.cc/apps/raspored/current/tmp/pids/thin.pid
log: /stor/www/public/bkrsta.co.cc/apps/raspored/current/log/thin.log
max_conns: 1024
timeout: 10
max_persistent_conns: 512
daemonize: true
